#!/bin/bash
# Git clone commands for all repositories
# Generated for user: jirihylmar
# Auto-generated by generate-clone-list.sh on Tue Nov 11 11:52:31 CET 2025

# ============================================
# BM-Nutritech (6 repositories)
# ============================================
git clone git@github.com:BM-Nutritech/nutritech-base.git
git clone git@github.com:BM-Nutritech/nutritech-kms.git
git clone git@github.com:BM-Nutritech/nutritech-mobile.git
git clone git@github.com:BM-Nutritech/nutritech-office.git
git clone git@github.com:BM-Nutritech/nutritech-thirdparty.git
git clone git@github.com:BM-Nutritech/nutritech-webapp.git

# ============================================
# Danse4mobility (87 repositories)
# ============================================
git clone git@github.com:Danse4mobility/2020-human-body.git
git clone git@github.com:Danse4mobility/app-cognito-manager.git
git clone git@github.com:Danse4mobility/aps-docker-d4m-rocker-geospatial.git
git clone git@github.com:Danse4mobility/aps-google-earth.git
git clone git@github.com:Danse4mobility/aps-hpc-execution-api.git
git clone git@github.com:Danse4mobility/aps-hpc-execution-management.git
git clone git@github.com:Danse4mobility/aps-image-postprocessing.git
git clone git@github.com:Danse4mobility/aps-parametersCore-dansup.git
git clone git@github.com:Danse4mobility/aps-resources.git
git clone git@github.com:Danse4mobility/aps-terminology.git
git clone git@github.com:Danse4mobility/aps-timeseries-cleaning-model.git
git clone git@github.com:Danse4mobility/aps-video-stream-capturing.git
git clone git@github.com:Danse4mobility/bh6-distributionStack.git
git clone git@github.com:Danse4mobility/bh6-sck-autacc.git
git clone git@github.com:Danse4mobility/bh6-sck-curdat.git
git clone git@github.com:Danse4mobility/bh6-sck-danter.git
git clone git@github.com:Danse4mobility/bh6-sck-geocovcel.git
git clone git@github.com:Danse4mobility/bh6-sck-geovislea.git
git clone git@github.com:Danse4mobility/bh6-sck-intevanet.git
git clone git@github.com:Danse4mobility/bh6-sck-intnetsta.git
git clone git@github.com:Danse4mobility/bh6-sck-secsam.git
git clone git@github.com:Danse4mobility/bh6-sck-spetereva.git
git clone git@github.com:Danse4mobility/bh6-sck-speter.git
git clone git@github.com:Danse4mobility/bh6-sck-tramod.git
git clone git@github.com:Danse4mobility/bh6-sck-watwor.git
git clone git@github.com:Danse4mobility/big-ilg-cor16a.git
git clone git@github.com:Danse4mobility/big-ilg-cor55a.git
git clone git@github.com:Danse4mobility/big-ilg-cor56a.git
git clone git@github.com:Danse4mobility/big-ilg-cordev.git
git clone git@github.com:Danse4mobility/big-intelligence.git
git clone git@github.com:Danse4mobility/big-sck-cor12a.git
git clone git@github.com:Danse4mobility/big-sck-cor12c.git
git clone git@github.com:Danse4mobility/big-sck-icopic.git
git clone git@github.com:Danse4mobility/big-sck-infdas.git
git clone git@github.com:Danse4mobility/big-sck-intanaadh.git
git clone git@github.com:Danse4mobility/big-sck-intevasec.git
git clone git@github.com:Danse4mobility/big-sck-parcor.git
git clone git@github.com:Danse4mobility/big-sck-prsrop.git
git clone git@github.com:Danse4mobility/big-sck-storage.git
git clone git@github.com:Danse4mobility/brm-bi-tools.git
git clone git@github.com:Danse4mobility/cvut-export.git
git clone git@github.com:Danse4mobility/d4m-sck-imanor.git
git clone git@github.com:Danse4mobility/d4m-sck-manpro.git
git clone git@github.com:Danse4mobility/d4m-sck-man.git
git clone git@github.com:Danse4mobility/d4m-sck-texpar.git
git clone git@github.com:Danse4mobility/develop-human-body.git
git clone git@github.com:Danse4mobility/develop-video-feedback-zones.git
git clone git@github.com:Danse4mobility/dkr-geo-getCell.git
git clone git@github.com:Danse4mobility/dkr-mkdocs-material.git
git clone git@github.com:Danse4mobility/dkr-ubuntu-build.git
git clone git@github.com:Danse4mobility/doc-api-delivery.git
git clone git@github.com:Danse4mobility/doc-data-processing.git
git clone git@github.com:Danse4mobility/doc-hpc-workflow.git
git clone git@github.com:Danse4mobility/doc-infrastructure.git
git clone git@github.com:Danse4mobility/doc-insiders.git
git clone git@github.com:Danse4mobility/doc-internship.git
git clone git@github.com:Danse4mobility/doc-ipr.git
git clone git@github.com:Danse4mobility/doc-mkDocs-boilerplate.git
git clone git@github.com:Danse4mobility/doc-neuropal.git
git clone git@github.com:Danse4mobility/doc-ropid.git
git clone git@github.com:Danse4mobility/doc-workflow.git
git clone git@github.com:Danse4mobility/enable-resource-domain-d4m.git
git clone git@github.com:Danse4mobility/fro-danse-portal.git
git clone git@github.com:Danse4mobility/fro-danse.git
git clone git@github.com:Danse4mobility/fro-ipr-portal.git
git clone git@github.com:Danse4mobility/fro-jsonvisio.git
git clone git@github.com:Danse4mobility/fro-ropid-portal.git
git clone git@github.com:Danse4mobility/fro-vue3-boilerplate.git
git clone git@github.com:Danse4mobility/hpc-pri-job-run.git
git clone git@github.com:Danse4mobility/infra-human-body.git
git clone git@github.com:Danse4mobility/inicom.git
git clone git@github.com:Danse4mobility/inicro.git
git clone git@github.com:Danse4mobility/inienv.git
git clone git@github.com:Danse4mobility/iot-dev-danse-tech.git
git clone git@github.com:Danse4mobility/lib-dfmmetadata.git
git clone git@github.com:Danse4mobility/new-web-danse.git
git clone git@github.com:Danse4mobility/oai-assistants-d4m.git
git clone git@github.com:Danse4mobility/prj-ropid.git
git clone git@github.com:Danse4mobility/resource-domain-d4m.git
git clone git@github.com:Danse4mobility/rodos-backup.git
git clone git@github.com:Danse4mobility/stk-api-delivery.git
git clone git@github.com:Danse4mobility/stk-api-ipr.git
git clone git@github.com:Danse4mobility/stk-api-ropid.git
git clone git@github.com:Danse4mobility/tmp-geodb-to-aws.git
git clone git@github.com:Danse4mobility/useful_public.git
git clone git@github.com:Danse4mobility/vsb-training-1.git
git clone git@github.com:Danse4mobility/web-danse-tech.git

# ============================================
# DigitalHorizonCz (16 repositories)
# ============================================
git clone git@github.com:DigitalHorizonCz/app-brm-manufacturing-dictionary.git
git clone git@github.com:DigitalHorizonCz/app-brm-manufacturing-products.git
git clone git@github.com:DigitalHorizonCz/app-brm-manufacturing-rendered-specifications-view.git
git clone git@github.com:DigitalHorizonCz/app-brm-manufacturing-render.git
git clone git@github.com:DigitalHorizonCz/app-cross-platform-browser-search.git
git clone git@github.com:DigitalHorizonCz/app-llm-inference-local.git
git clone git@github.com:DigitalHorizonCz/app-llm-training-local.git
git clone git@github.com:DigitalHorizonCz/app-model-compare.git
git clone git@github.com:DigitalHorizonCz/app-model-sql-t5.git
git clone git@github.com:DigitalHorizonCz/aps-brm-dictionaries.git
git clone git@github.com:DigitalHorizonCz/aps-brm-transform-labels.git
git clone git@github.com:DigitalHorizonCz/aps-digital-horizon-platform.git
git clone git@github.com:DigitalHorizonCz/hub400-mcp-local.git
git clone git@github.com:DigitalHorizonCz/hub400-mcp-manage.git
git clone git@github.com:DigitalHorizonCz/hub400-mcp.git
git clone git@github.com:DigitalHorizonCz/projects-brm-digital-horizon.git

# ============================================
# MasterIT-technologies-a-s (4 repositories)
# ============================================
git clone git@github.com:MasterIT-technologies-a-s/claude-mongodb-example.git
git clone git@github.com:MasterIT-technologies-a-s/databridge.git
git clone git@github.com:MasterIT-technologies-a-s/mitt-databridge-phase-1-models-compared-llm.git
git clone git@github.com:MasterIT-technologies-a-s/mitt-databridge-phase-1-report.git

# ============================================
# jirihylmar (6 repositories)
# ============================================
git clone git@github.com:jirihylmar/aps-goldsport-facebook.git
git clone git@github.com:jirihylmar/aps-pages-installers.git
git clone git@github.com:jirihylmar/doc-zoneiot.git
git clone git@github.com:jirihylmar/hyl-amplify-logs.git
git clone git@github.com:jirihylmar/mkdocs-material.git
git clone git@github.com:jirihylmar/my-brain-digital-horizon.git

# ============================================
# Summary:
# Total: 119 repositories across 5 organizations
# - BM-Nutritech: 6 repos
# - Danse4mobility: 87 repos
# - DigitalHorizonCz: 16 repos
# - MasterIT-technologies-a-s: 4 repos
# - jirihylmar: 6 repos
# ============================================
