#!/bin/bash
# Script to generate git clone commands for all accessible GitHub repositories
# This script queries GitHub API using stored credentials and generates a sorted list

set -e

# Output files
OUTPUT_FILE="git-clone-commands.sh"
MAPPING_FILE="workspace-repos.json"

# Get GitHub token from git credentials
GITHUB_TOKEN=$(grep "github.com" ~/.git-credentials | sed 's/https:\/\/.*:\(ghp_[^@]*\)@github.com/\1/')

if [ -z "$GITHUB_TOKEN" ]; then
    echo "Error: GitHub token not found in ~/.git-credentials"
    exit 1
fi

echo "Found GitHub token, querying repositories..."

# Create temporary files for storing repo data
TEMP_DIR=$(mktemp -d)
REPOS_FILE="$TEMP_DIR/repos.txt"

# Function to fetch repos from an organization
fetch_org_repos() {
    local org=$1
    echo "Fetching repos from organization: $org"
    local page=1
    local has_more=true

    while [ "$has_more" = true ]; do
        local response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/orgs/$org/repos?per_page=100&page=$page")

        # Check if response has any repos
        local repo_count=$(echo "$response" | jq '. | length')

        if [ "$repo_count" -eq 0 ]; then
            has_more=false
        else
            echo "$response" | jq -r '.[] | "\(.full_name)|\(.clone_url)|\(.archived)|\(.updated_at)"' >> "$REPOS_FILE"
            echo "  - Fetched page $page ($repo_count repos)"
            page=$((page + 1))
        fi
    done
}

# Function to fetch user's personal repos (owner only, not org repos)
fetch_user_repos() {
    local username=$1
    echo "Fetching personal repositories for $username (including private)..."
    local page=1
    local has_more=true
    local user_total=0

    while [ "$has_more" = true ]; do
        local response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/user/repos?per_page=100&page=$page&visibility=all&affiliation=owner")

        # Check if response has any repos
        local repo_count=$(echo "$response" | jq '. | length')

        if [ "$repo_count" -eq 0 ]; then
            has_more=false
        else
            # Filter for repos owned by the authenticated user (not org repos)
            local user_repos=$(echo "$response" | jq -r --arg user "$username" \
                '.[] | select(.owner.login == $user) | "\(.full_name)|\(.clone_url)|\(.archived)|\(.updated_at)"')

            if [ -n "$user_repos" ]; then
                echo "$user_repos" >> "$REPOS_FILE"
                local user_count=$(echo "$user_repos" | wc -l)
                user_total=$((user_total + user_count))
                echo "  - Fetched page $page ($user_count personal repos)"
            fi

            page=$((page + 1))
        fi
    done

    echo "  - Total personal repos: $user_total"
}

# Get authenticated user info
echo "Getting user information..."
USERNAME=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    "https://api.github.com/user" | jq -r '.login')

echo "Authenticated as: $USERNAME"

# Get list of organizations
echo "Getting organization list..."
ORGS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    "https://api.github.com/user/orgs" | jq -r '.[].login')

# Clear the repos file
> "$REPOS_FILE"

# Fetch personal repos
fetch_user_repos "$USERNAME"

# Fetch repos from each organization
for org in $ORGS; do
    fetch_org_repos "$org"
done

# Sort repos by organization and name, removing duplicates
echo "Sorting repositories and removing duplicates..."
sort -u "$REPOS_FILE" > "$TEMP_DIR/sorted_repos.txt"

# Generate the output script
echo "Generating $OUTPUT_FILE..."

cat > "$OUTPUT_FILE" <<HEADER
#!/bin/bash
# Git clone commands for all repositories
# Generated for user: $USERNAME
# Auto-generated by generate-clone-list.sh on $(date)

HEADER

# Group repos by organization
current_org=""
org_count=0

while IFS='|' read -r full_name https_url archived updated_at; do
    org=$(echo "$full_name" | cut -d'/' -f1)

    if [ "$org" != "$current_org" ]; then
        if [ -n "$current_org" ]; then
            echo "" >> "$OUTPUT_FILE"
        fi

        # Count repos for this org
        repo_count=$(grep "^$org/" "$TEMP_DIR/sorted_repos.txt" | wc -l)

        echo "# ============================================" >> "$OUTPUT_FILE"
        echo "# $org ($repo_count repositories)" >> "$OUTPUT_FILE"
        echo "# ============================================" >> "$OUTPUT_FILE"

        current_org="$org"
        org_count=$((org_count + 1))
    fi

    echo "git clone $https_url" >> "$OUTPUT_FILE"
done < "$TEMP_DIR/sorted_repos.txt"

# Add summary
total_repos=$(wc -l < "$TEMP_DIR/sorted_repos.txt")

cat >> "$OUTPUT_FILE" <<FOOTER

# ============================================
# Summary:
# Total: $total_repos repositories across $org_count organizations
FOOTER

# List org counts
while IFS='|' read -r full_name ssh_url archived updated_at; do
    echo "$full_name" | cut -d'/' -f1
done < "$TEMP_DIR/sorted_repos.txt" | sort | uniq -c | while read count org; do
    echo "# - $org: $count repos" >> "$OUTPUT_FILE"
done

echo "# ============================================" >> "$OUTPUT_FILE"

# Make output script executable
chmod +x "$OUTPUT_FILE"

# ============================================
# Generate JSON mapping file for workspace script
# ============================================
echo "Generating $MAPPING_FILE..."

echo "{" > "$MAPPING_FILE"

# Create JSON mapping of repo_name -> {git_url, archived, updated_at}
first=true
while IFS='|' read -r full_name https_url archived updated_at; do
    repo_name=$(echo "$full_name" | cut -d'/' -f2)

    if [ "$first" = true ]; then
        first=false
    else
        echo "," >> "$MAPPING_FILE"
    fi

    # Use jq to properly escape strings and format JSON
    printf "  \"%s\": {\"url\": \"%s\", \"archived\": %s, \"updated_at\": \"%s\"}" \
        "$repo_name" "$https_url" "$archived" "$updated_at" >> "$MAPPING_FILE"
done < "$TEMP_DIR/sorted_repos.txt"

echo "" >> "$MAPPING_FILE"
echo "}" >> "$MAPPING_FILE"

# Clean up
rm -rf "$TEMP_DIR"

echo "✓ Generated $OUTPUT_FILE"
echo "✓ Generated $MAPPING_FILE"
echo "✓ Total repositories: $total_repos"
echo "✓ Organizations: $org_count"
