#!/bin/bash
# Git clone commands for all repositories
# Generated for user: jirihylmar
# Auto-generated by generate-clone-list.sh on Fri Mar 27 17:31:45 CET 2026

# ============================================
# BM-Nutritech (7 repositories)
# ============================================
git clone https://github.com/BM-Nutritech/nutritech-base.git
git clone https://github.com/BM-Nutritech/nutritech-kms.git
git clone https://github.com/BM-Nutritech/nutritech-mobile.git
git clone https://github.com/BM-Nutritech/nutritech-office.git
git clone https://github.com/BM-Nutritech/nutritech-reports.git
git clone https://github.com/BM-Nutritech/nutritech-thirdparty.git
git clone https://github.com/BM-Nutritech/nutritech-webapp.git

# ============================================
# Danse4mobility (86 repositories)
# ============================================
git clone https://github.com/Danse4mobility/2020-human-body.git
git clone https://github.com/Danse4mobility/aps-docker-d4m-rocker-geospatial.git
git clone https://github.com/Danse4mobility/aps-google-earth.git
git clone https://github.com/Danse4mobility/aps-hpc-execution-api.git
git clone https://github.com/Danse4mobility/aps-hpc-execution-management.git
git clone https://github.com/Danse4mobility/aps-image-postprocessing.git
git clone https://github.com/Danse4mobility/aps-parametersCore-dansup.git
git clone https://github.com/Danse4mobility/aps-resources.git
git clone https://github.com/Danse4mobility/aps-terminology.git
git clone https://github.com/Danse4mobility/aps-timeseries-cleaning-model.git
git clone https://github.com/Danse4mobility/aps-video-stream-capturing.git
git clone https://github.com/Danse4mobility/bh6-distributionStack.git
git clone https://github.com/Danse4mobility/bh6-sck-autacc.git
git clone https://github.com/Danse4mobility/bh6-sck-curdat.git
git clone https://github.com/Danse4mobility/bh6-sck-danter.git
git clone https://github.com/Danse4mobility/bh6-sck-geocovcel.git
git clone https://github.com/Danse4mobility/bh6-sck-geovislea.git
git clone https://github.com/Danse4mobility/bh6-sck-intevanet.git
git clone https://github.com/Danse4mobility/bh6-sck-intnetsta.git
git clone https://github.com/Danse4mobility/bh6-sck-secsam.git
git clone https://github.com/Danse4mobility/bh6-sck-spetereva.git
git clone https://github.com/Danse4mobility/bh6-sck-speter.git
git clone https://github.com/Danse4mobility/bh6-sck-tramod.git
git clone https://github.com/Danse4mobility/bh6-sck-watwor.git
git clone https://github.com/Danse4mobility/big-ilg-cor16a.git
git clone https://github.com/Danse4mobility/big-ilg-cor55a.git
git clone https://github.com/Danse4mobility/big-ilg-cor56a.git
git clone https://github.com/Danse4mobility/big-ilg-cordev.git
git clone https://github.com/Danse4mobility/big-intelligence.git
git clone https://github.com/Danse4mobility/big-sck-cor12a.git
git clone https://github.com/Danse4mobility/big-sck-cor12c.git
git clone https://github.com/Danse4mobility/big-sck-icopic.git
git clone https://github.com/Danse4mobility/big-sck-infdas.git
git clone https://github.com/Danse4mobility/big-sck-intanaadh.git
git clone https://github.com/Danse4mobility/big-sck-intevasec.git
git clone https://github.com/Danse4mobility/big-sck-parcor.git
git clone https://github.com/Danse4mobility/big-sck-prsrop.git
git clone https://github.com/Danse4mobility/big-sck-storage.git
git clone https://github.com/Danse4mobility/brm-bi-tools.git
git clone https://github.com/Danse4mobility/cvut-export.git
git clone https://github.com/Danse4mobility/d4m-sck-imanor.git
git clone https://github.com/Danse4mobility/d4m-sck-manpro.git
git clone https://github.com/Danse4mobility/d4m-sck-man.git
git clone https://github.com/Danse4mobility/d4m-sck-texpar.git
git clone https://github.com/Danse4mobility/develop-human-body.git
git clone https://github.com/Danse4mobility/develop-video-feedback-zones.git
git clone https://github.com/Danse4mobility/dkr-geo-getCell.git
git clone https://github.com/Danse4mobility/dkr-mkdocs-material.git
git clone https://github.com/Danse4mobility/dkr-ubuntu-build.git
git clone https://github.com/Danse4mobility/doc-api-delivery.git
git clone https://github.com/Danse4mobility/doc-data-processing.git
git clone https://github.com/Danse4mobility/doc-hpc-workflow.git
git clone https://github.com/Danse4mobility/doc-infrastructure.git
git clone https://github.com/Danse4mobility/doc-insiders.git
git clone https://github.com/Danse4mobility/doc-internship.git
git clone https://github.com/Danse4mobility/doc-ipr.git
git clone https://github.com/Danse4mobility/doc-mkDocs-boilerplate.git
git clone https://github.com/Danse4mobility/doc-neuropal.git
git clone https://github.com/Danse4mobility/doc-ropid.git
git clone https://github.com/Danse4mobility/doc-workflow.git
git clone https://github.com/Danse4mobility/enable-resource-domain-d4m.git
git clone https://github.com/Danse4mobility/fro-danse-portal.git
git clone https://github.com/Danse4mobility/fro-danse.git
git clone https://github.com/Danse4mobility/fro-ipr-portal.git
git clone https://github.com/Danse4mobility/fro-jsonvisio.git
git clone https://github.com/Danse4mobility/fro-ropid-portal.git
git clone https://github.com/Danse4mobility/fro-vue3-boilerplate.git
git clone https://github.com/Danse4mobility/hpc-pri-job-run.git
git clone https://github.com/Danse4mobility/infra-human-body.git
git clone https://github.com/Danse4mobility/inicom.git
git clone https://github.com/Danse4mobility/inicro.git
git clone https://github.com/Danse4mobility/inienv.git
git clone https://github.com/Danse4mobility/iot-dev-danse-tech.git
git clone https://github.com/Danse4mobility/lib-dfmmetadata.git
git clone https://github.com/Danse4mobility/new-web-danse.git
git clone https://github.com/Danse4mobility/oai-assistants-d4m.git
git clone https://github.com/Danse4mobility/prj-ropid.git
git clone https://github.com/Danse4mobility/resource-domain-d4m.git
git clone https://github.com/Danse4mobility/rodos-backup.git
git clone https://github.com/Danse4mobility/stk-api-delivery.git
git clone https://github.com/Danse4mobility/stk-api-ipr.git
git clone https://github.com/Danse4mobility/stk-api-ropid.git
git clone https://github.com/Danse4mobility/tmp-geodb-to-aws.git
git clone https://github.com/Danse4mobility/useful_public.git
git clone https://github.com/Danse4mobility/vsb-training-1.git
git clone https://github.com/Danse4mobility/web-danse-tech.git

# ============================================
# DigitalHorizonCz (35 repositories)
# ============================================
git clone https://github.com/DigitalHorizonCz/app-brm-manufacturing-dictionary.git
git clone https://github.com/DigitalHorizonCz/app-brm-manufacturing-products.git
git clone https://github.com/DigitalHorizonCz/app-cross-platform-browser-search.git
git clone https://github.com/DigitalHorizonCz/app-llm-inference-local.git
git clone https://github.com/DigitalHorizonCz/app-llm-training-local.git
git clone https://github.com/DigitalHorizonCz/app-model-compare.git
git clone https://github.com/DigitalHorizonCz/app-model-sql-t5.git
git clone https://github.com/DigitalHorizonCz/aps-brm-dictionaries.git
git clone https://github.com/DigitalHorizonCz/aps-brm-products-backend.git
git clone https://github.com/DigitalHorizonCz/aps-brm-products-infrastructure.git
git clone https://github.com/DigitalHorizonCz/aps-brm-products-playbook.git
git clone https://github.com/DigitalHorizonCz/aps-brm-transform-labels.git
git clone https://github.com/DigitalHorizonCz/aps-digital-horizon-platform.git
git clone https://github.com/DigitalHorizonCz/aps-goldsport-video-feedback-playbook.git
git clone https://github.com/DigitalHorizonCz/broadcast-admin-frontend.git
git clone https://github.com/DigitalHorizonCz/broadcast-infrastructure.git
git clone https://github.com/DigitalHorizonCz/broadcast-orchestration.git
git clone https://github.com/DigitalHorizonCz/digital-horizon-platform.git
git clone https://github.com/DigitalHorizonCz/digital-horizon-playbook.git
git clone https://github.com/DigitalHorizonCz/goldsport-video-feedback-backend.git
git clone https://github.com/DigitalHorizonCz/goldsport-video-feedback-frontend.git
git clone https://github.com/DigitalHorizonCz/goldsport-video-feedback-infrastructure.git
git clone https://github.com/DigitalHorizonCz/hub400-mcp-local.git
git clone https://github.com/DigitalHorizonCz/hub400-mcp-manage.git
git clone https://github.com/DigitalHorizonCz/hub400-mcp.git
git clone https://github.com/DigitalHorizonCz/hub440-mcp-test-playbook.git
git clone https://github.com/DigitalHorizonCz/mcp-orchestration.git
git clone https://github.com/DigitalHorizonCz/projects-brm-digital-horizon.git
git clone https://github.com/DigitalHorizonCz/sck-brm-eurlex.git
git clone https://github.com/DigitalHorizonCz/useiot-frontend-admin.git
git clone https://github.com/DigitalHorizonCz/useiot-frontend-user.git
git clone https://github.com/DigitalHorizonCz/useiot-infrastructure.git
git clone https://github.com/DigitalHorizonCz/useiot-inspect-devices.git
git clone https://github.com/DigitalHorizonCz/useiot-orchestration.git
git clone https://github.com/DigitalHorizonCz/useiot-testing.git

# ============================================
# MasterIT-technologies-a-s (5 repositories)
# ============================================
git clone https://github.com/MasterIT-technologies-a-s/claude-mongodb-example.git
git clone https://github.com/MasterIT-technologies-a-s/databridge-data-migrator.git
git clone https://github.com/MasterIT-technologies-a-s/mitt-databridge-api.git
git clone https://github.com/MasterIT-technologies-a-s/mitt-databridge-phase-1-models-compared-llm.git
git clone https://github.com/MasterIT-technologies-a-s/mitt-databridge-phase-1-report.git

# ============================================
# hub440-syndicate (12 repositories)
# ============================================
git clone https://github.com/hub440-syndicate/bills-hub440.git
git clone https://github.com/hub440-syndicate/mcp-docker-connectors.git
git clone https://github.com/hub440-syndicate/mcp-docker-infrastructure.git
git clone https://github.com/hub440-syndicate/mcp-docker-playbook.git
git clone https://github.com/hub440-syndicate/mcp-docker-solutions.git
git clone https://github.com/hub440-syndicate/mcp-goldsport-skischool.git
git clone https://github.com/hub440-syndicate/mcp-mitt-databridge.git
git clone https://github.com/hub440-syndicate/rss-mitt-voucher-application.git
git clone https://github.com/hub440-syndicate/rss-mitt-voucher.git
git clone https://github.com/hub440-syndicate/syndicate-infrastructure.git
git clone https://github.com/hub440-syndicate/syndicate-playbooks-examples.git
git clone https://github.com/hub440-syndicate/syndicate-playbook.git

# ============================================
# jirihylmar (47 repositories)
# ============================================
git clone https://github.com/jirihylmar/app-claude-query.git
git clone https://github.com/jirihylmar/app-dynamo-digital-horizon-manager.git
git clone https://github.com/jirihylmar/app-dynamo-metadata-manager.git
git clone https://github.com/jirihylmar/app-s3-metadata-manager.git
git clone https://github.com/jirihylmar/aps-digital-horizon-platform.git
git clone https://github.com/jirihylmar/aps-digital-horizon-questionnaires.git
git clone https://github.com/jirihylmar/aps-digital-horizon-reporter.git
git clone https://github.com/jirihylmar/aps-digital-horizon-v0.git
git clone https://github.com/jirihylmar/aps-goldsport-analytics.git
git clone https://github.com/jirihylmar/aps-goldsport-booking-sheets.git
git clone https://github.com/jirihylmar/aps-goldsport-booking.git
git clone https://github.com/jirihylmar/aps-goldsport-events.git
git clone https://github.com/jirihylmar/aps-goldsport-facebook.git
git clone https://github.com/jirihylmar/aps-goldsport-messaging.git
git clone https://github.com/jirihylmar/aps-goldsport-page-reviews.git
git clone https://github.com/jirihylmar/aps-goldsport-pages.git
git clone https://github.com/jirihylmar/aps-goldsport-scheduler.git
git clone https://github.com/jirihylmar/aps-goldsport-twilio.git
git clone https://github.com/jirihylmar/aps-pages-installers.git
git clone https://github.com/jirihylmar/doc-digital-horizon-goldsport.git
git clone https://github.com/jirihylmar/doc-nutritech.git
git clone https://github.com/jirihylmar/doc-zoneiot.git
git clone https://github.com/jirihylmar/goldsport-messaging.git
git clone https://github.com/jirihylmar/help.git
git clone https://github.com/jirihylmar/hyl-amplify-logs.git
git clone https://github.com/jirihylmar/hyl-arduino.git
git clone https://github.com/jirihylmar/hyl-assistants.git
git clone https://github.com/jirihylmar/hyl-bibliography.git
git clone https://github.com/jirihylmar/hyl-dictionaries.git
git clone https://github.com/jirihylmar/hyl-digital-horizon.git
git clone https://github.com/jirihylmar/hyl-flashcards.git
git clone https://github.com/jirihylmar/hyl-graphics.git
git clone https://github.com/jirihylmar/hyl-library.git
git clone https://github.com/jirihylmar/hyl-media.git
git clone https://github.com/jirihylmar/hyl-render.git
git clone https://github.com/jirihylmar/hyl-resources-manager.git
git clone https://github.com/jirihylmar/hyl-sck-med.git
git clone https://github.com/jirihylmar/hyl-screenshot.git
git clone https://github.com/jirihylmar/hyl-web.git
git clone https://github.com/jirihylmar/iniaut.git
git clone https://github.com/jirihylmar/lib-dfmrender.git
git clone https://github.com/jirihylmar/mkdocs-material.git
git clone https://github.com/jirihylmar/my-brain-digital-horizon.git
git clone https://github.com/jirihylmar/neu-sck-rc4ann.git
git clone https://github.com/jirihylmar/zoneiot-collectors-firmware-infdev.git
git clone https://github.com/jirihylmar/zoneiot-collectors-provision-infdev.git
git clone https://github.com/jirihylmar/zoneiot-iotsystems-infdev.git

# ============================================
# Summary:
# Total: 192 repositories across 6 organizations
# - BM-Nutritech: 7 repos
# - Danse4mobility: 86 repos
# - DigitalHorizonCz: 35 repos
# - MasterIT-technologies-a-s: 5 repos
# - hub440-syndicate: 12 repos
# - jirihylmar: 47 repos
# ============================================
