#!/bin/bash
# Git clone/update commands for workspace repositories
# Inspects .code-workspace files and manages repositories
# Checks if repos exist in $HOME or /mnt/c/Users/jirih, updates or clones as needed

set -e

# ============================================
# Configuration
# ============================================
WORKSPACE_DIR="$HOME"
SEARCH_LOCATIONS=("$HOME" "/mnt/c/Users/jirih")
WORKSPACE_FILES=(
    "metadata.code-workspace"
    "goldsport.code-workspace"
    "manufacturing.code-workspace"
    "models.code-workspace"
    "databridge.code-workspace"
    "docs.code-workspace"
    "system.code-workspace"
    "digital-horizon.code-workspace"
    "iot.code-workspace"
)

# Path to the repo mapping file (generated by generate-clone-list.sh)
REPO_MAPPING_FILE="$(dirname "$0")/workspace-repos.json"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# ============================================
# Functions
# ============================================

# Extract repository paths from workspace file
extract_repos_from_workspace() {
    local workspace_file="$1"

    if [[ ! -f "$workspace_file" ]]; then
        echo -e "${RED}Warning: Workspace file not found: $workspace_file${NC}" >&2
        return 1
    fi

    # Extract "path" values from JSON, filter out comments and extract repo names
    grep -oP '"path":\s*"\K[^"]+' "$workspace_file" | while read -r path; do
        # Extract just the directory name (repo name)
        basename "$path"
    done
}

# Check if a repository exists in any of the search locations
find_repo_location() {
    local repo_name="$1"

    for location in "${SEARCH_LOCATIONS[@]}"; do
        local repo_path="$location/$repo_name"
        if [[ -d "$repo_path/.git" ]]; then
            echo "$repo_path"
            return 0
        fi
    done

    return 1
}

# Update an existing repository
update_repo() {
    local repo_path="$1"
    local repo_name=$(basename "$repo_path")

    echo -e "${BLUE}Updating: $repo_name${NC}"

    cd "$repo_path"

    # Fetch latest changes
    if git fetch --all 2>/dev/null; then
        # Get current branch
        local current_branch=$(git rev-parse --abbrev-ref HEAD)

        # Check if there are incoming changes
        local local_commit=$(git rev-parse HEAD)
        local remote_commit=$(git rev-parse origin/$current_branch 2>/dev/null || echo "")

        if [[ -n "$remote_commit" && "$local_commit" != "$remote_commit" ]]; then
            # Check if working directory is clean
            if git diff-index --quiet HEAD -- 2>/dev/null; then
                git pull origin "$current_branch"
                echo -e "${GREEN}✓ Updated: $repo_name${NC}"
            else
                echo -e "${YELLOW}⚠ Skipped: $repo_name (has uncommitted changes)${NC}"
            fi
        else
            echo -e "${GREEN}✓ Up to date: $repo_name${NC}"
        fi
    else
        echo -e "${RED}✗ Failed to fetch: $repo_name${NC}"
    fi

    cd - > /dev/null
}

# Clone a new repository
clone_repo() {
    local repo_name="$1"
    local github_url="$2"
    local target_dir="${3:-$HOME}"

    echo -e "${BLUE}Cloning: $repo_name${NC}"

    cd "$target_dir"

    if git clone "$github_url" 2>/dev/null; then
        echo -e "${GREEN}✓ Cloned: $repo_name${NC}"
    else
        echo -e "${RED}✗ Failed to clone: $repo_name${NC}"
    fi

    cd - > /dev/null
}

# Get GitHub URL from repository mapping file
get_github_url() {
    local repo_name="$1"

    # Check if mapping file exists
    if [[ ! -f "$REPO_MAPPING_FILE" ]]; then
        echo -e "${RED}Error: Repo mapping file not found at $REPO_MAPPING_FILE${NC}" >&2
        echo -e "${RED}Run generate-clone-list.sh first to create the mapping.${NC}" >&2
        return 1
    fi

    # Try to get URL from mapping file using jq
    local git_url=$(jq -r --arg repo "$repo_name" '.[$repo] // empty' "$REPO_MAPPING_FILE" 2>/dev/null)

    if [[ -n "$git_url" ]]; then
        echo "$git_url"
    else
        echo -e "${RED}Error: $repo_name not found in mapping file${NC}" >&2
        echo -e "${RED}Repository may not exist or mapping file is outdated${NC}" >&2
        return 1
    fi
}

# Process a repository (update if exists, clone if not)
process_repo() {
    local repo_name="$1"

    # Try to find existing repo
    local existing_path=$(find_repo_location "$repo_name")

    if [[ -n "$existing_path" ]]; then
        # Repository exists, update it
        update_repo "$existing_path"
    else
        # Repository doesn't exist, get URL from mapping and clone
        local github_url=$(get_github_url "$repo_name")

        # Check if get_github_url succeeded
        if [[ $? -eq 0 && -n "$github_url" ]]; then
            clone_repo "$repo_name" "$github_url" "${SEARCH_LOCATIONS[0]}"
        else
            echo -e "${RED}✗ Skipped: $repo_name (URL not found in mapping)${NC}"
        fi
    fi
}

# ============================================
# Main Script
# ============================================

echo "============================================"
echo "Workspace Repository Manager"
echo "============================================"
echo ""

# Track all unique repositories
declare -A all_repos
declare -A missing_repos
declare -A updated_repos
declare -A cloned_repos
declare -A uptodate_repos

# Process each workspace file
for workspace_file in "${WORKSPACE_FILES[@]}"; do
    workspace_path="$WORKSPACE_DIR/$workspace_file"

    if [[ ! -f "$workspace_path" ]]; then
        echo -e "${YELLOW}Skipping: $workspace_file (not found)${NC}"
        continue
    fi

    echo -e "${BLUE}Processing workspace: $workspace_file${NC}"

    # Extract and process repositories
    while IFS= read -r repo_name; do
        if [[ -n "$repo_name" ]]; then
            all_repos["$repo_name"]=1
        fi
    done < <(extract_repos_from_workspace "$workspace_path")

    echo ""
done

# Check for missing repos in mapping
echo "============================================"
echo "Checking repository mapping..."
echo "============================================"
echo ""

for repo_name in "${!all_repos[@]}"; do
    if ! jq -e --arg repo "$repo_name" '.[$repo]' "$REPO_MAPPING_FILE" > /dev/null 2>&1; then
        missing_repos["$repo_name"]=1
        echo -e "${YELLOW}⚠ Warning: $repo_name not found in mapping${NC}"
    fi
done

if [ ${#missing_repos[@]} -gt 0 ]; then
    echo ""
    echo -e "${YELLOW}Found ${#missing_repos[@]} repositories not in GitHub mapping${NC}"
    echo -e "${YELLOW}These repos may be local-only or need to be created on GitHub${NC}"
fi

echo ""

# Process all unique repositories
echo "============================================"
echo "Processing repositories..."
echo "============================================"
echo ""

for repo_name in "${!all_repos[@]}"; do
    process_repo "$repo_name"
done

echo ""
echo "============================================"
echo "Summary"
echo "============================================"
echo "Total repos in workspaces: ${#all_repos[@]}"
echo "Missing from GitHub: ${#missing_repos[@]}"
if [ ${#missing_repos[@]} -gt 0 ]; then
    echo ""
    echo "Repos not found in GitHub mapping:"
    for repo in "${!missing_repos[@]}"; do
        echo "  - $repo"
    done
fi
echo "============================================"
